#! /bin/sh

# Desktop freeze measures at the start of rofi
yay -S --rebuild rofi

# install mozc_config.desktop and icon.svg
sudo curl https://raw.githubusercontent.com/mitsugu/mozc_config/main/mozc_config.desktop -o /usr/share/applications/mozc_config.desktop
sudo curl https://raw.githubusercontent.com/google/mozc/master/src/data/images/product_icon_32bpp-128.png -o /usr/share/icons/hicolor/128x128/status/mozc.png

# add shorcut for mozc_tool
echo 'bindsym $mod+m exec --no-startup-id /usr/lib/mozc/mozc_tool --mode=config_dialog' >> ~/.config/i3/config

